//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reg
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class REGDBEntities : DbContext
    {
        public REGDBEntities()
            : base("name=REGDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Ranks> Ranks { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<Teams_Users> Teams_Users { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
