//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int team_id { get; set; }
        public int current_week { get; set; }
        public Nullable<int> summ_coef { get; set; }
        public Nullable<double> efficiency { get; set; }
        public int salary { get; set; }
    
        public virtual Teams Teams { get; set; }
        public virtual Users Users { get; set; }
    }
}
